# Practical Application III: Comparing Classifiers

**Overview**: In this practical application, your goal is to compare the performance of the classifiers we encountered in this section, namely K Nearest Neighbor, Logistic Regression, Decision Trees, and Support Vector Machines.  We will utilize a dataset related to marketing bank products over the telephone.  



### Getting Started

Our dataset comes from the UCI Machine Learning repository [link](https://archive.ics.uci.edu/ml/datasets/bank+marketing).  The data is from a Portugese banking institution and is a collection of the results of multiple marketing campaigns.  We will make use of the article accompanying the dataset [here](CRISP-DM-BANK.pdf) for more information on the data and features.



### Problem 1: Understanding the Data

To gain a better understanding of the data, please read the information provided in the UCI link above, and examine the **Materials and Methods** section of the paper.  How many marketing campaigns does this data represent?

In [1]:
### This dataset shows 17 marketing campaigns by a Portuguese bank between 2008 and 20010 which included about 80 thousand phone contacts.
### The full CSV contains about 40,000 contacts with 20 different input features. 

### Problem 2: Read in the Data

Use pandas to read in the dataset `bank-additional-full.csv` and assign to a meaningful variable name.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"E:\module17_starter\data\bank-additional-full.csv", sep = ';')

In [4]:
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no


### Problem 3: Understanding the Features


Examine the data description below, and determine if any of the features are missing values or need to be coerced to a different data type.


```
Input variables:
# bank client data:
1 - age (numeric)
2 - job : type of job (categorical: 'admin.','blue-collar','entrepreneur','housemaid','management','retired','self-employed','services','student','technician','unemployed','unknown')
3 - marital : marital status (categorical: 'divorced','married','single','unknown'; note: 'divorced' means divorced or widowed)
4 - education (categorical: 'basic.4y','basic.6y','basic.9y','high.school','illiterate','professional.course','university.degree','unknown')
5 - default: has credit in default? (categorical: 'no','yes','unknown')
6 - housing: has housing loan? (categorical: 'no','yes','unknown')
7 - loan: has personal loan? (categorical: 'no','yes','unknown')
# related with the last contact of the current campaign:
8 - contact: contact communication type (categorical: 'cellular','telephone')
9 - month: last contact month of year (categorical: 'jan', 'feb', 'mar', ..., 'nov', 'dec')
10 - day_of_week: last contact day of the week (categorical: 'mon','tue','wed','thu','fri')
11 - duration: last contact duration, in seconds (numeric). Important note: this attribute highly affects the output target (e.g., if duration=0 then y='no'). Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model.
# other attributes:
12 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)
13 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric; 999 means client was not previously contacted)
14 - previous: number of contacts performed before this campaign and for this client (numeric)
15 - poutcome: outcome of the previous marketing campaign (categorical: 'failure','nonexistent','success')
# social and economic context attributes
16 - emp.var.rate: employment variation rate - quarterly indicator (numeric)
17 - cons.price.idx: consumer price index - monthly indicator (numeric)
18 - cons.conf.idx: consumer confidence index - monthly indicator (numeric)
19 - euribor3m: euribor 3 month rate - daily indicator (numeric)
20 - nr.employed: number of employees - quarterly indicator (numeric)

Output variable (desired target):
21 - y - has the client subscribed a term deposit? (binary: 'yes','no')
```



In [5]:
df.info()
(df == 'unknown').sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

age                  0
job                330
marital             80
education         1731
default           8597
housing            990
loan               990
contact              0
month                0
day_of_week          0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx       0
cons.conf.idx        0
euribor3m            0
nr.employed          0
y                    0
dtype: int64

### Problem 4: Understanding the Task

After examining the description and data, your goal now is to clearly state the *Business Objective* of the task.  State the objective below.

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

I think that business objective of this task is to improve the portugese banks efficiency of its telemarketing comapigns for deposit subscriptions. This would allow the bank to target specific clients that are most likely to subscribe.

### Problem 5: Engineering Features

Now that you understand your business objective, we will build a basic model to get started.  Before we can do this, we must work to encode the data.  Using just the bank information features, prepare the features and target column for modeling with appropriate encoding and transformations.

In [8]:
bank_features = ['age', 'job', 'marital', 'education', 'default', 'housing', 'loan']

X = df[bank_features].copy()
y = df['y'].map({'no': 0, 'yes': 1})

In [9]:
X_encoded = pd.get_dummies(X, drop_first = True)

X_encoded.head()

,age,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,...,education_illiterate,education_professional.course,education_university.degree,education_unknown,default_unknown,default_yes,housing_unknown,housing_yes,loan_unknown,loan_yes
0,56,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,57,False,False,False,False,False,False,True,False,False,...,False,False,False,False,True,False,False,False,False,False
2,37,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
3,40,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,56,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,True


In [10]:
print("Feature matrix shape:", X_encoded.shape)
print("Target distribution:\n", y.value_counts(normalize=True))

Feature matrix shape: (41188, 28)
Target distribution:
 y
0    0.887346
1    0.112654
Name: proportion, dtype: float64


### Problem 6: Train/Test Split

With your data prepared, split it into a train and test set.

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y,
    test_size = 0.3,
    random_state = 42,
    stratify = y
)

In [12]:
print("Train:", X_train.shape, " Test:", X_test.shape)
print("\nTrain target balance:\n", y_train.value_counts(normalize=True))
print("\nTest target balance:\n", y_test.value_counts(normalize=True))

Train: (28831, 28)  Test: (12357, 28)

Train target balance:
 y
0    0.887343
1    0.112657
Name: proportion, dtype: float64

Test target balance:
 y
0    0.887351
1    0.112649
Name: proportion, dtype: float64


### Problem 7: A Baseline Model

Before we build our first model, we want to establish a baseline.  What is the baseline performance that our classifier should aim to beat?

In [13]:
from sklearn.dummy import DummyClassifier

baseline = DummyClassifier(strategy = 'most_frequent')
baseline.fit(X_train, y_train)

baseline_acc = baseline.score(X_test, y_test)
print("Baseline (always predict 'no') accuracy: ", baseline_acc)

Baseline (always predict 'no') accuracy:  0.8873512988589464


The baseline performance that our classifier should aim to beat is 88.7% accuracy. If it is beloy than it is doing wrose than no model at all. 

### Problem 8: A Simple Model

Use Logistic Regression to build a basic model on your data.  

In [14]:
from sklearn.linear_model import LogisticRegression

lgr = LogisticRegression(max_iter = 1000)
lgr.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


### Problem 9: Score the Model

What is the accuracy of your model?

In [15]:
train_acc = lgr.score(X_train, y_train)
test_acc = lgr.score(X_test, y_test)

print("Logistic Regression train accuracy: ", train_acc)
print("Logistic Regression test accuracy: ", test_acc)
print("Baseline accuracy: ", baseline_acc)

Logistic Regression train accuracy:  0.8873434844438278
Logistic Regression test accuracy:  0.8873512988589464
Baseline accuracy:  0.8873512988589464


### Problem 10: Model Comparisons

Now, we aim to compare the performance of the Logistic Regression model to our KNN algorithm, Decision Tree, and SVM models.  Using the default settings for each of the models, fit and score each.  Also, be sure to compare the fit time of each of the models.  Present your findings in a `DataFrame` similar to that below:

| Model | Train Time | Train Accuracy | Test Accuracy |
| ----- | ---------- | -------------  | -----------   |
|     |    |.     |.     |

In [16]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
import time

In [17]:
lgr = LogisticRegression(max_iter = 1000)
start = time.time()
lgr.fit(X_train, y_train)
lgr_time = time.time() - start

lgr_train = lgr.score(X_train, y_train)
lgr_test = lgr.score(X_test, y_test)
print("Logistic Regression done -- time: ", lgr_time)

Logistic Regression done -- time:  0.36339831352233887


In [18]:
knn = KNeighborsClassifier()
start = time.time()
knn.fit(X_train, y_train)
knn_time = time.time() - start

knn_train = knn.score(X_train, y_train)
knn_test = knn.score(X_test, y_test)
print("KNN done -- time: :", knn_time)

KNN done -- time: : 0.01311492919921875


In [19]:
tree = DecisionTreeClassifier()
start = time.time()
tree.fit(X_train, y_train)
tree_time = time.time() - start

tree_train = tree.score(X_train, y_train)
tree_test = tree.score(X_test, y_test)
print("Decision tree done -- time: ", tree_time)

Decision tree done -- time:  0.08775448799133301


In [20]:
svm = SVC()
start = time.time()
svm.fit(X_train, y_train)
svm_time = time.time() - start

svm_train = svm.score(X_train, y_train)
svm_test = svm.score(X_test, y_test)
print("SVM done -- time: ", svm_time)

SVM done -- time:  9.58661699295044


In [21]:
results_df = pd.DataFrame({
    'Model':          ['Logistic Regression', 'KNN', 'Decision Tree', 'SVM'],
    'Train Time':     [lgr_time, knn_time, tree_time, svm_time],
    'Train Accuracy': [lgr_train, knn_train, tree_train, svm_train],
    'Test Accuracy':  [lgr_test, knn_test, tree_test, svm_test],
})
results_df

,Model,Train Time,Train Accuracy,Test Accuracy
0,Logistic Regression,0.363398,0.887343,0.887351
1,KNN,0.013115,0.890985,0.875293
2,Decision Tree,0.087754,0.918837,0.864368
3,SVM,9.586617,0.887343,0.887351


### Problem 11: Improving the Model

Now that we have some basic models on the board, we want to try to improve these.  Below, we list a few things to explore in this pursuit.


- Hyperparameter tuning and grid search.  All of our models have additional hyperparameters to tune and explore.  For example the number of neighbors in KNN or the maximum depth of a Decision Tree.  
- Adjust your performance metric

In [22]:
from sklearn.metrics import classification_report

for name, model in [('Logistic Regression', lgr), ('KNN', knn),
                    ('Decision Tree', tree), ('SVM', svm)]:
    print(f"\n=== {name} ===")
    print(classification_report(y_test, model.predict(X_test), digits=3))


=== Logistic Regression ===
              precision    recall  f1-score   support

           0      0.887     1.000     0.940     10965
           1      0.000     0.000     0.000      1392

    accuracy                          0.887     12357
   macro avg      0.444     0.500     0.470     12357
weighted avg      0.787     0.887     0.834     12357


=== KNN ===


E:\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
E:\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
E:\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


              precision    recall  f1-score   support

           0      0.893     0.976     0.933     10965
           1      0.298     0.079     0.125      1392

    accuracy                          0.875     12357
   macro avg      0.596     0.528     0.529     12357
weighted avg      0.826     0.875     0.842     12357


=== Decision Tree ===
              precision    recall  f1-score   support

           0      0.893     0.963     0.926     10965
           1      0.233     0.089     0.129      1392

    accuracy                          0.864     12357
   macro avg      0.563     0.526     0.528     12357
weighted avg      0.818     0.864     0.837     12357


=== SVM ===
              precision    recall  f1-score   support

           0      0.887     1.000     0.940     10965
           1      0.000     0.000     0.000      1392

    accuracy                          0.887     12357
   macro avg      0.444     0.500     0.470     12357
weighted avg      0.787     0.887     

E:\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
E:\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
E:\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [24]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

lgr_grid = GridSearchCV(
    LogisticRegression(max_iter=1000, class_weight='balanced'),
    {'C': [0.01, 0.1, 1, 10]},
    scoring='f1', cv=5, n_jobs=-1
)
lgr_grid.fit(X_train, y_train)
print("Best params:", lgr_grid.best_params_, "| CV F1:", lgr_grid.best_score_)

Best params: {'C': 0.1} | CV F1: 0.25568281696210365


In [25]:
knn_grid = GridSearchCV(
    Pipeline([('scale', StandardScaler()), ('knn', KNeighborsClassifier())]),
    {'knn__n_neighbors': [11, 21, 31]},
    scoring='f1', cv=5, n_jobs=-1
)
knn_grid.fit(X_train, y_train)
print("Best params:", knn_grid.best_params_, "| CV F1:", knn_grid.best_score_)

Best params: {'knn__n_neighbors': 11} | CV F1: 0.05491012296966089


In [26]:
tree_grid = GridSearchCV(
    DecisionTreeClassifier(class_weight='balanced', random_state=42),
    {'max_depth': [3, 5, 10], 'min_samples_leaf': [1, 5, 20]},
    scoring='f1', cv=5, n_jobs=-1
)
tree_grid.fit(X_train, y_train)
print("Best params:", tree_grid.best_params_, "| CV F1:", tree_grid.best_score_)

Best params: {'max_depth': 5, 'min_samples_leaf': 1} | CV F1: 0.255974431773565


In [27]:
svm_bal = SVC(class_weight='balanced')
svm_bal.fit(X_train, y_train)
print("Balanced SVM fitted")

Balanced SVM fitted


In [28]:
from sklearn.metrics import f1_score

tuned = {
    'Logistic Regression': lgr_grid.best_estimator_,
    'KNN':                 knn_grid.best_estimator_,
    'Decision Tree':       tree_grid.best_estimator_,
    'SVM (balanced)':      svm_bal,
}

improved_df = pd.DataFrame([
    {'Model': name,
     'Test Accuracy': m.score(X_test, y_test),
     'Test F1 (class=yes)': f1_score(y_test, m.predict(X_test))}
    for name, m in tuned.items()
])
improved_df

,Model,Test Accuracy,Test F1 (class=yes)
0,Logistic Regression,0.590839,0.256252
1,KNN,0.885571,0.062334
2,Decision Tree,0.698794,0.265878
3,SVM (balanced),0.677268,0.255970


Based on only bank client features, Logistic Regression and SVM scored about 88.7% accuracy by predicting the clients responses, "no". finding zero subscribers. f1 created a model that could actually detect subscribers. After the grid search, the Decision Tree gave the best F1 with Logistic Regression and SVM being close up and coming. The accuracy fell for those a little bit because they predicted "yes" for the likely subscribers instead of going back to "no", which is a valid switch because the banks goal was to catch subscribers. 
My main reccomendation to the bank is to improve the targeting by incorporating features from the banks caompaign and other economic features so that other variables can be evauluated on their recall instead of accuracy alone. 

##### Questions